services:
  - type: web
    name: backoffice-front
    runtime: static
    buildCommand: corepack enable && pnpm install --frozen-lockfile && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
