/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlterarSenhaObrigatoriaRouteImport } from './routes/alterar-senha-obrigatoria'
import { Route as PatrocinadorRouteRouteImport } from './routes/patrocinador/route'
import { Route as MembroRouteRouteImport } from './routes/membro/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatrocinadorIndexRouteImport } from './routes/patrocinador/index'
import { Route as MembroIndexRouteImport } from './routes/membro/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ValidarContaTokenRouteImport } from './routes/validar-conta/$token'
import { Route as PatrocinadorHistoricoRouteImport } from './routes/patrocinador/historico'
import { Route as PatrocinadorCheckInRouteImport } from './routes/patrocinador/check-in'
import { Route as PatrocinadorBeneficiosRouteImport } from './routes/patrocinador/beneficios'
import { Route as MembroHistoricoRouteImport } from './routes/membro/historico'
import { Route as MembroCarteirinhaRouteImport } from './routes/membro/carteirinha'
import { Route as AdminPatrocinadoresIndexRouteImport } from './routes/admin/patrocinadores/index'
import { Route as AdminMensalidadesIndexRouteImport } from './routes/admin/mensalidades/index'
import { Route as AdminBeneficiosIndexRouteImport } from './routes/admin/beneficios/index'
import { Route as AdminAssociadosIndexRouteImport } from './routes/admin/associados/index'
import { Route as AdminPatrocinadoresNovoRouteImport } from './routes/admin/patrocinadores/novo'
import { Route as AdminAssociadosNovoRouteImport } from './routes/admin/associados/novo'
import { Route as AdminAssociadosUserIdRouteImport } from './routes/admin/associados/$userId'
import { Route as AdminPatrocinadoresUserIdEditarRouteImport } from './routes/admin/patrocinadores/$userId/editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaObrigatoriaRoute = AlterarSenhaObrigatoriaRouteImport.update({
  id: '/alterar-senha-obrigatoria',
  path: '/alterar-senha-obrigatoria',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadorRouteRoute = PatrocinadorRouteRouteImport.update({
  id: '/patrocinador',
  path: '/patrocinador',
  getParentRoute: () => rootRouteImport,
} as any)
const MembroRouteRoute = MembroRouteRouteImport.update({
  id: '/membro',
  path: '/membro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadorIndexRoute = PatrocinadorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatrocinadorRouteRoute,
} as any)
const MembroIndexRoute = MembroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembroRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ValidarContaTokenRoute = ValidarContaTokenRouteImport.update({
  id: '/validar-conta/$token',
  path: '/validar-conta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadorHistoricoRoute = PatrocinadorHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => PatrocinadorRouteRoute,
} as any)
const PatrocinadorCheckInRoute = PatrocinadorCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => PatrocinadorRouteRoute,
} as any)
const PatrocinadorBeneficiosRoute = PatrocinadorBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => PatrocinadorRouteRoute,
} as any)
const MembroHistoricoRoute = MembroHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => MembroRouteRoute,
} as any)
const MembroCarteirinhaRoute = MembroCarteirinhaRouteImport.update({
  id: '/carteirinha',
  path: '/carteirinha',
  getParentRoute: () => MembroRouteRoute,
} as any)
const AdminPatrocinadoresIndexRoute =
  AdminPatrocinadoresIndexRouteImport.update({
    id: '/patrocinadores/',
    path: '/patrocinadores/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminMensalidadesIndexRoute = AdminMensalidadesIndexRouteImport.update({
  id: '/mensalidades/',
  path: '/mensalidades/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBeneficiosIndexRoute = AdminBeneficiosIndexRouteImport.update({
  id: '/beneficios/',
  path: '/beneficios/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssociadosIndexRoute = AdminAssociadosIndexRouteImport.update({
  id: '/associados/',
  path: '/associados/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPatrocinadoresNovoRoute = AdminPatrocinadoresNovoRouteImport.update({
  id: '/patrocinadores/novo',
  path: '/patrocinadores/novo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssociadosNovoRoute = AdminAssociadosNovoRouteImport.update({
  id: '/associados/novo',
  path: '/associados/novo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssociadosUserIdRoute = AdminAssociadosUserIdRouteImport.update({
  id: '/associados/$userId',
  path: '/associados/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPatrocinadoresUserIdEditarRoute =
  AdminPatrocinadoresUserIdEditarRouteImport.update({
    id: '/patrocinadores/$userId/editar',
    path: '/patrocinadores/$userId/editar',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/membro': typeof MembroRouteRouteWithChildren
  '/patrocinador': typeof PatrocinadorRouteRouteWithChildren
  '/alterar-senha-obrigatoria': typeof AlterarSenhaObrigatoriaRoute
  '/login': typeof LoginRoute
  '/membro/carteirinha': typeof MembroCarteirinhaRoute
  '/membro/historico': typeof MembroHistoricoRoute
  '/patrocinador/beneficios': typeof PatrocinadorBeneficiosRoute
  '/patrocinador/check-in': typeof PatrocinadorCheckInRoute
  '/patrocinador/historico': typeof PatrocinadorHistoricoRoute
  '/validar-conta/$token': typeof ValidarContaTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/membro/': typeof MembroIndexRoute
  '/patrocinador/': typeof PatrocinadorIndexRoute
  '/admin/associados/$userId': typeof AdminAssociadosUserIdRoute
  '/admin/associados/novo': typeof AdminAssociadosNovoRoute
  '/admin/patrocinadores/novo': typeof AdminPatrocinadoresNovoRoute
  '/admin/associados/': typeof AdminAssociadosIndexRoute
  '/admin/beneficios/': typeof AdminBeneficiosIndexRoute
  '/admin/mensalidades/': typeof AdminMensalidadesIndexRoute
  '/admin/patrocinadores/': typeof AdminPatrocinadoresIndexRoute
  '/admin/patrocinadores/$userId/editar': typeof AdminPatrocinadoresUserIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alterar-senha-obrigatoria': typeof AlterarSenhaObrigatoriaRoute
  '/login': typeof LoginRoute
  '/membro/carteirinha': typeof MembroCarteirinhaRoute
  '/membro/historico': typeof MembroHistoricoRoute
  '/patrocinador/beneficios': typeof PatrocinadorBeneficiosRoute
  '/patrocinador/check-in': typeof PatrocinadorCheckInRoute
  '/patrocinador/historico': typeof PatrocinadorHistoricoRoute
  '/validar-conta/$token': typeof ValidarContaTokenRoute
  '/admin': typeof AdminIndexRoute
  '/membro': typeof MembroIndexRoute
  '/patrocinador': typeof PatrocinadorIndexRoute
  '/admin/associados/$userId': typeof AdminAssociadosUserIdRoute
  '/admin/associados/novo': typeof AdminAssociadosNovoRoute
  '/admin/patrocinadores/novo': typeof AdminPatrocinadoresNovoRoute
  '/admin/associados': typeof AdminAssociadosIndexRoute
  '/admin/beneficios': typeof AdminBeneficiosIndexRoute
  '/admin/mensalidades': typeof AdminMensalidadesIndexRoute
  '/admin/patrocinadores': typeof AdminPatrocinadoresIndexRoute
  '/admin/patrocinadores/$userId/editar': typeof AdminPatrocinadoresUserIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/membro': typeof MembroRouteRouteWithChildren
  '/patrocinador': typeof PatrocinadorRouteRouteWithChildren
  '/alterar-senha-obrigatoria': typeof AlterarSenhaObrigatoriaRoute
  '/login': typeof LoginRoute
  '/membro/carteirinha': typeof MembroCarteirinhaRoute
  '/membro/historico': typeof MembroHistoricoRoute
  '/patrocinador/beneficios': typeof PatrocinadorBeneficiosRoute
  '/patrocinador/check-in': typeof PatrocinadorCheckInRoute
  '/patrocinador/historico': typeof PatrocinadorHistoricoRoute
  '/validar-conta/$token': typeof ValidarContaTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/membro/': typeof MembroIndexRoute
  '/patrocinador/': typeof PatrocinadorIndexRoute
  '/admin/associados/$userId': typeof AdminAssociadosUserIdRoute
  '/admin/associados/novo': typeof AdminAssociadosNovoRoute
  '/admin/patrocinadores/novo': typeof AdminPatrocinadoresNovoRoute
  '/admin/associados/': typeof AdminAssociadosIndexRoute
  '/admin/beneficios/': typeof AdminBeneficiosIndexRoute
  '/admin/mensalidades/': typeof AdminMensalidadesIndexRoute
  '/admin/patrocinadores/': typeof AdminPatrocinadoresIndexRoute
  '/admin/patrocinadores/$userId/editar': typeof AdminPatrocinadoresUserIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/membro'
    | '/patrocinador'
    | '/alterar-senha-obrigatoria'
    | '/login'
    | '/membro/carteirinha'
    | '/membro/historico'
    | '/patrocinador/beneficios'
    | '/patrocinador/check-in'
    | '/patrocinador/historico'
    | '/validar-conta/$token'
    | '/admin/'
    | '/membro/'
    | '/patrocinador/'
    | '/admin/associados/$userId'
    | '/admin/associados/novo'
    | '/admin/patrocinadores/novo'
    | '/admin/associados/'
    | '/admin/beneficios/'
    | '/admin/mensalidades/'
    | '/admin/patrocinadores/'
    | '/admin/patrocinadores/$userId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alterar-senha-obrigatoria'
    | '/login'
    | '/membro/carteirinha'
    | '/membro/historico'
    | '/patrocinador/beneficios'
    | '/patrocinador/check-in'
    | '/patrocinador/historico'
    | '/validar-conta/$token'
    | '/admin'
    | '/membro'
    | '/patrocinador'
    | '/admin/associados/$userId'
    | '/admin/associados/novo'
    | '/admin/patrocinadores/novo'
    | '/admin/associados'
    | '/admin/beneficios'
    | '/admin/mensalidades'
    | '/admin/patrocinadores'
    | '/admin/patrocinadores/$userId/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/membro'
    | '/patrocinador'
    | '/alterar-senha-obrigatoria'
    | '/login'
    | '/membro/carteirinha'
    | '/membro/historico'
    | '/patrocinador/beneficios'
    | '/patrocinador/check-in'
    | '/patrocinador/historico'
    | '/validar-conta/$token'
    | '/admin/'
    | '/membro/'
    | '/patrocinador/'
    | '/admin/associados/$userId'
    | '/admin/associados/novo'
    | '/admin/patrocinadores/novo'
    | '/admin/associados/'
    | '/admin/beneficios/'
    | '/admin/mensalidades/'
    | '/admin/patrocinadores/'
    | '/admin/patrocinadores/$userId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MembroRouteRoute: typeof MembroRouteRouteWithChildren
  PatrocinadorRouteRoute: typeof PatrocinadorRouteRouteWithChildren
  AlterarSenhaObrigatoriaRoute: typeof AlterarSenhaObrigatoriaRoute
  LoginRoute: typeof LoginRoute
  ValidarContaTokenRoute: typeof ValidarContaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha-obrigatoria': {
      id: '/alterar-senha-obrigatoria'
      path: '/alterar-senha-obrigatoria'
      fullPath: '/alterar-senha-obrigatoria'
      preLoaderRoute: typeof AlterarSenhaObrigatoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinador': {
      id: '/patrocinador'
      path: '/patrocinador'
      fullPath: '/patrocinador'
      preLoaderRoute: typeof PatrocinadorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membro': {
      id: '/membro'
      path: '/membro'
      fullPath: '/membro'
      preLoaderRoute: typeof MembroRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinador/': {
      id: '/patrocinador/'
      path: '/'
      fullPath: '/patrocinador/'
      preLoaderRoute: typeof PatrocinadorIndexRouteImport
      parentRoute: typeof PatrocinadorRouteRoute
    }
    '/membro/': {
      id: '/membro/'
      path: '/'
      fullPath: '/membro/'
      preLoaderRoute: typeof MembroIndexRouteImport
      parentRoute: typeof MembroRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/validar-conta/$token': {
      id: '/validar-conta/$token'
      path: '/validar-conta/$token'
      fullPath: '/validar-conta/$token'
      preLoaderRoute: typeof ValidarContaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinador/historico': {
      id: '/patrocinador/historico'
      path: '/historico'
      fullPath: '/patrocinador/historico'
      preLoaderRoute: typeof PatrocinadorHistoricoRouteImport
      parentRoute: typeof PatrocinadorRouteRoute
    }
    '/patrocinador/check-in': {
      id: '/patrocinador/check-in'
      path: '/check-in'
      fullPath: '/patrocinador/check-in'
      preLoaderRoute: typeof PatrocinadorCheckInRouteImport
      parentRoute: typeof PatrocinadorRouteRoute
    }
    '/patrocinador/beneficios': {
      id: '/patrocinador/beneficios'
      path: '/beneficios'
      fullPath: '/patrocinador/beneficios'
      preLoaderRoute: typeof PatrocinadorBeneficiosRouteImport
      parentRoute: typeof PatrocinadorRouteRoute
    }
    '/membro/historico': {
      id: '/membro/historico'
      path: '/historico'
      fullPath: '/membro/historico'
      preLoaderRoute: typeof MembroHistoricoRouteImport
      parentRoute: typeof MembroRouteRoute
    }
    '/membro/carteirinha': {
      id: '/membro/carteirinha'
      path: '/carteirinha'
      fullPath: '/membro/carteirinha'
      preLoaderRoute: typeof MembroCarteirinhaRouteImport
      parentRoute: typeof MembroRouteRoute
    }
    '/admin/patrocinadores/': {
      id: '/admin/patrocinadores/'
      path: '/patrocinadores'
      fullPath: '/admin/patrocinadores/'
      preLoaderRoute: typeof AdminPatrocinadoresIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/mensalidades/': {
      id: '/admin/mensalidades/'
      path: '/mensalidades'
      fullPath: '/admin/mensalidades/'
      preLoaderRoute: typeof AdminMensalidadesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/beneficios/': {
      id: '/admin/beneficios/'
      path: '/beneficios'
      fullPath: '/admin/beneficios/'
      preLoaderRoute: typeof AdminBeneficiosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/associados/': {
      id: '/admin/associados/'
      path: '/associados'
      fullPath: '/admin/associados/'
      preLoaderRoute: typeof AdminAssociadosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patrocinadores/novo': {
      id: '/admin/patrocinadores/novo'
      path: '/patrocinadores/novo'
      fullPath: '/admin/patrocinadores/novo'
      preLoaderRoute: typeof AdminPatrocinadoresNovoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/associados/novo': {
      id: '/admin/associados/novo'
      path: '/associados/novo'
      fullPath: '/admin/associados/novo'
      preLoaderRoute: typeof AdminAssociadosNovoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/associados/$userId': {
      id: '/admin/associados/$userId'
      path: '/associados/$userId'
      fullPath: '/admin/associados/$userId'
      preLoaderRoute: typeof AdminAssociadosUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patrocinadores/$userId/editar': {
      id: '/admin/patrocinadores/$userId/editar'
      path: '/patrocinadores/$userId/editar'
      fullPath: '/admin/patrocinadores/$userId/editar'
      preLoaderRoute: typeof AdminPatrocinadoresUserIdEditarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAssociadosUserIdRoute: typeof AdminAssociadosUserIdRoute
  AdminAssociadosNovoRoute: typeof AdminAssociadosNovoRoute
  AdminPatrocinadoresNovoRoute: typeof AdminPatrocinadoresNovoRoute
  AdminAssociadosIndexRoute: typeof AdminAssociadosIndexRoute
  AdminBeneficiosIndexRoute: typeof AdminBeneficiosIndexRoute
  AdminMensalidadesIndexRoute: typeof AdminMensalidadesIndexRoute
  AdminPatrocinadoresIndexRoute: typeof AdminPatrocinadoresIndexRoute
  AdminPatrocinadoresUserIdEditarRoute: typeof AdminPatrocinadoresUserIdEditarRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAssociadosUserIdRoute: AdminAssociadosUserIdRoute,
  AdminAssociadosNovoRoute: AdminAssociadosNovoRoute,
  AdminPatrocinadoresNovoRoute: AdminPatrocinadoresNovoRoute,
  AdminAssociadosIndexRoute: AdminAssociadosIndexRoute,
  AdminBeneficiosIndexRoute: AdminBeneficiosIndexRoute,
  AdminMensalidadesIndexRoute: AdminMensalidadesIndexRoute,
  AdminPatrocinadoresIndexRoute: AdminPatrocinadoresIndexRoute,
  AdminPatrocinadoresUserIdEditarRoute: AdminPatrocinadoresUserIdEditarRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface MembroRouteRouteChildren {
  MembroCarteirinhaRoute: typeof MembroCarteirinhaRoute
  MembroHistoricoRoute: typeof MembroHistoricoRoute
  MembroIndexRoute: typeof MembroIndexRoute
}

const MembroRouteRouteChildren: MembroRouteRouteChildren = {
  MembroCarteirinhaRoute: MembroCarteirinhaRoute,
  MembroHistoricoRoute: MembroHistoricoRoute,
  MembroIndexRoute: MembroIndexRoute,
}

const MembroRouteRouteWithChildren = MembroRouteRoute._addFileChildren(
  MembroRouteRouteChildren,
)

interface PatrocinadorRouteRouteChildren {
  PatrocinadorBeneficiosRoute: typeof PatrocinadorBeneficiosRoute
  PatrocinadorCheckInRoute: typeof PatrocinadorCheckInRoute
  PatrocinadorHistoricoRoute: typeof PatrocinadorHistoricoRoute
  PatrocinadorIndexRoute: typeof PatrocinadorIndexRoute
}

const PatrocinadorRouteRouteChildren: PatrocinadorRouteRouteChildren = {
  PatrocinadorBeneficiosRoute: PatrocinadorBeneficiosRoute,
  PatrocinadorCheckInRoute: PatrocinadorCheckInRoute,
  PatrocinadorHistoricoRoute: PatrocinadorHistoricoRoute,
  PatrocinadorIndexRoute: PatrocinadorIndexRoute,
}

const PatrocinadorRouteRouteWithChildren =
  PatrocinadorRouteRoute._addFileChildren(PatrocinadorRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MembroRouteRoute: MembroRouteRouteWithChildren,
  PatrocinadorRouteRoute: PatrocinadorRouteRouteWithChildren,
  AlterarSenhaObrigatoriaRoute: AlterarSenhaObrigatoriaRoute,
  LoginRoute: LoginRoute,
  ValidarContaTokenRoute: ValidarContaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
